# Generated by Django 5.0.3 on 2024-03-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_login",
            name="username",
            field=models.CharField(default="", max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user_login",
            name="user_id",
            field=models.CharField(max_length=200),
        ),
    ]
