# Generated by Django 5.0.3 on 2024-05-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="subjects",
            field=models.CharField(default="Notification", max_length=255),
        ),
    ]
