# Generated by Django 5.0.3 on 2024-04-15 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="gpa",
        ),
    ]
