# Generated by Django 5.0.3 on 2024-04-26 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_alter_users_made_password"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="users",
            options={},
        ),
        migrations.AlterModelManagers(
            name="users",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="users",
            name="date_joined",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="users",
            name="password",
        ),
    ]
