# Generated by Django 5.0.3 on 2024-03-16 05:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_user_login_username_alter_user_login_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user_login",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="user_login",
            name="email",
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user_login",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
