# Generated by Django 5.0.3 on 2024-05-05 07:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_notification_subjects"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="subject",
        ),
    ]
