# Generated by Django 5.0.3 on 2024-05-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_remove_notification_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(max_length=255),
        ),
    ]
