# Generated by Django 5.0.3 on 2024-05-04 19:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_alter_users_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admins",
            name="is_superadmin",
        ),
        migrations.RemoveField(
            model_name="admins",
            name="is_superuser",
        ),
    ]
