# Generated by Django 5.0.3 on 2024-04-17 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0004_users_admins_user_notification_user"),
    ]

    operations = []
