# Generated by Django 5.0.3 on 2024-05-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0005_alter_notification_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="department",
            field=models.CharField(default="CSE", max_length=255),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(default="message"),
        ),
    ]
