# Generated by Django 5.0.3 on 2024-05-04 19:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0006_admins_is_superuser"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="admins",
            name="is_superuser",
        ),
    ]
