# Generated by Django 5.0.3 on 2024-04-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drives", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="drive",
            name="date",
        ),
        migrations.AddField(
            model_name="drive",
            name="drivedate",
            field=models.DateField(default="2024-4-24"),
        ),
        migrations.AddField(
            model_name="drive",
            name="lastdate",
            field=models.DateField(default="2024-4-24"),
        ),
    ]
