# Generated by Django 5.0.3 on 2024-04-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drives", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drive",
            name="bscklog",
            field=models.CharField(default="", max_length=10),
        ),
        migrations.AlterField(
            model_name="drive",
            name="gpa_limit",
            field=models.CharField(default="", max_length=10),
        ),
    ]
