# Generated by Django 5.0.3 on 2024-04-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Drives", "0002_remove_drive_date_drive_drivedate_drive_lastdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drive",
            name="position",
            field=models.CharField(max_length=100),
        ),
    ]
