# Generated by Django 5.0.3 on 2024-04-25 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Drives", "0003_alter_drive_position"),
    ]

    operations = [
        migrations.RenameField(
            model_name="drive",
            old_name="backlog",
            new_name="backlog_limit",
        ),
    ]
